openapi: 3.0.0

servers:
  - url: /1

info:
  description: >-
    Provides an OpenAPI-based REST interface to check voter
    registration.

  version: "1"
  title: Voter Registration Check
  contact:
    name: Reece Hart
    email: reecehart@gmail.com
    url: https://github.com/reece/voter-reg-check

paths:
  /regcheck/:
    post:
      summary: Check voter registration status
      operationId: voter_reg_check.routes.regcheck.post
      description: Checks voter registration status against Vote America
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoterInfo"

      responses:
        "200":
          description: >-
          content:
            text/plain:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  voter_info:
                    type: object

components:
  schemas:
    VoterInfo:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        street_address:
          type: string
        apartment:
          type: string
          default: ""
        city:
          type: string
        state:
          type: string
        zip_5:
          type: string
        dob:
          type: string
      required:
        - first_name
        - last_name
        - street_address
        - apartment
        - city
        - state
        - zip_5
        - dob
      example:
        first_name: "Joe"
        last_name: "Biden"
        street_address: "1600 Pennsylvania Ave. NW"
        apartment: ""
        city: "Washington"
        state: "DC"
        zip_5: "20500"
        dob: "11/20/1942"
        
        
