openapi: 3.0.0

servers:
  - url: /1

info:
  description: >-
    Provides an OpenAPI-based REST interface to check voter
    registration.

  version: "1"
  title: Voter Registration Check
  contact:
    name: Reece Hart
    email: reecehart@gmail.com
    url: https://github.com/reece/voter-reg-check

paths:
  /regcheck/:
    post:
      summary: Check voter registration status
      description: Checks voter registration status
      operationId: voter_reg_check.routes.regcheck.post
      requestBody:
        required: True
        content:
          application/json:
            schema:
              properties:
                method:
                  type: string
                  enum: ["rockthevote", "voteorg"]
                  description: >-
                    Keyword to select which backend service to use for
                    registration check
                voter_info:
                  $ref: "#/components/schemas/VoterInfo"
  
      responses:
        "200":
          description: >-
          content:
            text/plain:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    example: "2020-07-18T17:04:23.337332+00:00"
                  method:
                    type: string
                    example: "rockthevote"
                  result:
                    type: boolean
                    example: true
                  voter_info:
                    $ref: "#/components/schemas/VoterInfo"

components:
  schemas:
    VoterInfo:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        street_address:
          type: string
        apartment:
          type: string
          default: ""
        city:
          type: string
        state_abbrev:
          type: string
        zip_5:
          type: string
        dob:
          type: string
      required:
        - first_name
        - last_name
        - street_address
        - apartment
        - city
        - state_abbrev
        - zip_5
        - dob
      example:
        first_name: "Reece"
        last_name: "Hart"
        street_address: "1 Sussex St."
        apartment: ""
        city: "San Francisco"
        state_abbrev: "CA"
        zip_5: "94131"
        dob: "11/22/1968"
        
#        first_name: "Joe"
#        last_name: "Biden"
#        street_address: "1600 Pennsylvania Ave. NW"
#        apartment: ""
#        city: "Washington"
#        state_abbrev: "DC"
#        zip_5: "20500"
#        dob: "11/20/1942"
        
